{{- if .Values.keda.enabled }}
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: rag-aerospace
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: rag-aerospace
  pollingInterval: {{ .Values.keda.pollingInterval }}
  cooldownPeriod: {{ .Values.keda.cooldownPeriod }}
  minReplicaCount: {{ .Values.keda.minReplicaCount }}
  maxReplicaCount: {{ .Values.keda.maxReplicaCount }}
  triggers:
{{- range .Values.keda.triggers }}
    - type: {{ .type }}
      metadata:
{{ toYaml .metadata | indent 8 }}
{{- end }}
{{- end }}
